### ISSUE TITLE
Parallelize slowly running steps in the pipeline

### ISSUE THREAD

**Issue by ctcisar** [hubmapconsortium/spatial-transcriptomics-pipeline#48]
```[tasklist]
### Tasks
- [ ] Split input files into different folders to avoid over-requesting disk space
- [ ] Scatter input to step
  - [x] Decoding
  - [ ] Processing
- [x] Merge output from step
```
